// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://pg7w3nsnxbcmbae5okli5yjfda.appsync-api.ap-southeast-2.amazonaws.com/graphql',
          region: 'ap-southeast-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-7vmdo4hhfva2phfiazyihixt5e'
        }
    }
};

export default config;